services:
  - type: web
    name: sis-smpe
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn smpe.web:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        fromDatabase:
          name: sis-smpe-db
          property: connectionString

databases:
  - name: sis-smpe-db
    plan: free
    databaseName: smpe
    user: smpe
